### ISSUE TITLE
URLError when local file doesn't exist

### ISSUE THREAD

**Issue by sappjw** [jepler/leapseconddata#2]
When I try to get the list from a standard source:

    ls = leapseconddata.LeapSecondData.from_standard_source()

I get the following error:

    URLError: <urlopen error [Errno 2] No such file or directory: '/usr/share/zoneinfo/leap-seconds.list'>

I'm on a Linux system (CentOS 7).  `/usr/share/zoneinfo/leap-seconds` exists, but the above path does not.  It seems like this error could be caught.

**Comment by sappjw** [comment]
#3 looks like it resolves this issue after testing on the same machine.

**Comment by jepler** [comment]
What's the content of `/usr/share/zoneinfo/leap-seconds` on your centos machine? Is there a `leap-seconds.list` file installed in some other location, or in a package you can add?

Debian 11 has /usr/share/zoneinfo/leapseconds (wrong format) and /usr/share/zoneinfo/leap-seconds.list (right format). The right format should contain (after a large number of comment lines) data in this format:
```
2272060800      10      # 1 Jan 1972
2287785600      11      # 1 Jul 1972
```

**Comment by sappjw** [comment]
Looks like it's the wrong format (I had to rename [leapseconds](https://github.com/jepler/leapseconddata/files/8334741/leapseconds.txt) so I could upload).

**Comment by jepler** [comment]
Thanks for checking!
